### ISSUE TITLE
All the colors are broken

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1696]
- [x] In menu background color is wrong
- [x] Ingame in menu background is transparent
- [x] in tee selection all tees are black
That's a bit more bugs than expected.

**Comment by Learath2** [comment]
3cfbd83 fixes the first two

**Comment by def-** [comment]
Thanks.
Color for authed player got way darker.

**Comment by Learath2** [comment]
Fixed the color for the authed players, ui colors are now unpacked accurately, so the color we put there is actually darker.

**Comment by def-** [comment]
Now my tee colors are totally wrong.

But tees are no longer black in tee selection.

**Comment by def-** [comment]
![screenshot-20190501@195536](https://user-images.githubusercontent.com/2335377/57032605-19a37300-6c4b-11e9-969c-3274ac32f11f.png)

**Comment by Learath2** [comment]
ca888c56a fixes the colors being lightened twice, I'm not sure if this is the best way though :/

**Comment by def-** [comment]
No, it doesn't fix the issue. Every time I restart the client my tee gets brighter.

**Comment by Learath2** [comment]
Okay I missed that, b86c457 should fix that as well and it's a better fix overall imho.

**Comment by Learath2** [comment]
@def- I think that's everything, if you find anything else lmk
