### ISSUE TITLE
Undefined behaviour in snapshots

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#3049]
I found a funny bug again:

https://stackoverflow.com/questions/45429780/is-right-shifting-undefined-behavior-for-negative-number-in-cpp-and-in-java

I was profiling with MSVC under windows, and for some reason nameplates always called `LookupUuid`
which is quite inefficient (bcs its called for all clients every frame)

then i tried under linux.. couldn't reproduce.
then i analysed whats the difference between the two versions and found out that in snapshot.h
int Type() { return m_TypeAndID >> 16; }
does not return -1 under VC++ but 32767

**Comment by def-** [comment]
So let's just make it a `return m_TypeAndID <= 0 ? -1 : m_TypeAndID >> 16;`?

**Comment by Jupeyy** [comment]
i dunno that program, but im ok with ur patch :D

**Comment by Jupeyy** [comment]
ok zero must stay zero probably, but better ask heinrich for such details

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
@Jupeyy Can you give an example value for m_TypeAndID where you found a difference between Windows and Linux?

Right shift of negative integers is implementation defined in C, but all major compilers (MSVC, GCC, LLVM) seem to define it as arithmetic right shift, so it should guarantee same results. C++20 guarantees that it's arithmetic right shift, so I guess there's simply no compiler that implemented it differently (otherwise it's unlikely that it would have made it into the standard).

**Comment by Jupeyy** [comment]
Can only tell you what i did to reproduce, also i was on MSVC 2017 not 2019 so not impossible its a bug

in nameplates.cpp line 219 calls the snapshot stuff

i was on a empty ddnet server and in SnapFindItem

i was == 4
when:
`m_aSnapshots[g_Config.m_ClDummy][SnapID]->m_pAltSnap->GetItemType(i)`
was called, and the value from
int InternalType = GetItem(Index)->Type();
was -1 in linux and 32767 under windows

**Comment by heinrich5991** [comment]
MSVC documents that it always does arithmetic right shift (I guess they'd mention if that was ever not the case):

https://docs.microsoft.com/en-us/cpp/cpp/left-shift-and-right-shift-operators-input-and-output?view=vs-2019#right-shifts

> The result of a right-shift of a signed negative number is implementation-dependent. Although the Microsoft C++ compiler uses the sign bit to fill vacated bit positions, there is no guarantee that other implementations also do so.

**Comment by Jupeyy** [comment]
I still get a different snapshot under windows(MSVC) with current master code

**Comment by def-** [comment]
Could you maybe add some prints for debugging and to find out where the difference comes from if it's not from this?
